config/routes.rb
SocialThing::Application.routes.draw do

  resources :friend_circles

  resources :posts

  resources :links

  resources :friend_circle_memberships

  resources :users do
    collection do
      get "reset_password"
      get "fix_password"
    end
  end
  resource :session, only: [:new, :create, :destroy] do
    collection do
      get "forgot_password"
      put "send_email"
    end
  end
end

app/models/friend_circle.rb
class FriendCircle < ActiveRecord::Base
  attr_accessible :owner_id, :member_ids

  has_many :post_shares

  has_many :posts,
  through: :post_shares

  belongs_to :owner,
  class_name: "User",
  foreign_key: :owner_id

  has_many :friend_circle_memberships

  has_many :members,
  through: :friend_circle_memberships


end

app/models/friend_circle_membership.rb
class FriendCircleMembership < ActiveRecord::Base
  attr_accessible :friend_circle_id, :member_id

  belongs_to :friend_circle,
  foreign_key: :friend_circle_id

  belongs_to :member,
  class_name: "User",
  foreign_key: :member_id
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :post_id, :url
  validates :post, presence: true

  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :author_id, :body, :title, :link_attributes

  has_many :post_shares, inverse_of: :post

  has_many :links, inverse_of: :post

  has_many :friend_circles, through: :post_shares


  belongs_to :author,
  class_name: "User",
  foreign_key: :author_id
end

app/models/post_share.rb
class PostShare < ActiveRecord::Base
  attr_accessible :friend_circle_id, :post_id
  validates :post, presence: true

  belongs_to :post

  belongs_to :friend_circle


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :password, :token

  validates :email, :password_digest, :token,
  presence: true
  validates :email, uniqueness: { message: " That email is taken! "}
  after_initialize :ensure_token
  # don't validate password  EVERY TIME. doofus.
  validates :password, length: { minimum: 6, allow_nil: true }, on: :create

  has_many :managed_circles,
  foreign_key: :owner_id

  has_many :friend_circle_memberships,
  foreign_key: :member_id

  has_many :friend_circles,
    through: :friend_circle_memberships;



  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  # must define this alongside password=
  def password
    @password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_token
    self.token = SecureRandom.urlsafe_base64(16)
    self.save!
  end

  def generate_forgot_token
    self.forgot_password_token = SecureRandom.urlsafe_base64(16)
        self.save!
  end

  def ensure_token(force = true)
    self.token ||= SecureRandom.urlsafe_base64(16)
    self.save!
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    user.is_password?(password) ? user : nil

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user


  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_token(session[:session_token])
  end

  def login_user!(user)
    user.generate_token
    session[:session_token] = user.token
  end

end

app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController
  def new
    @users = User.all
    @owner = current_user
    @friend_circle = FriendCircle.new
    @current_members = []
  end

  def create
    @friend_circle = FriendCircle.new(params[:friend_circle])

    @friend_circle.member_ids = params[:friend_circle_memberships][:member_id]

    @friend_circle.save!

  end

  def edit
    @friend_circle = FriendCircle.includes(:friend_circle_memberships).find(params[:id])
    @users = User.all
    @current_members = FriendCircleMembership
      .where("friend_circle_memberships.friend_circle_id = ?", @friend_circle.id)
      .pluck(:member_id)

#:friend_circle_id, :member_id

  end

  def update
    @friend_circle = FriendCircle.find(params[:id])
    @friend_circle_membership = @friend_circle.friend_circle_memberships

    @current_members = FriendCircleMembership
      .where("friend_circle_memberships.friend_circle_id = ?", @friend_circle.id)
      .pluck(:member_id)

      @friend_circle.update_attributes!(params[:friend_circle_memberships])
 #   @friend_circle.

#    if params[:friend_circle_memberships] # ==> member_ids
  end

  def show
  end

  def index
  end

  def destroy
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end

  def destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    3.times { @post.links.build }

    @user_friend_circles = current_user.friend_circles

  end

  def create
    @post = Post.new(params[:post])
    @post.links.new(params[:link].values.compact)

    # if made :friend_circle_ids in the params hash via the form, can just grab
    # params[:post_share]
    @post.friend_circle_ids = params[:post_share][:friend_circle_id]

    # could skip post_share entirely because of @posts's has_many :through assoc, and then could just put :friend_circle_ids into the hash via the form

    # @friend_circle.member_ids = params[:friend_circle_memberships][:member_id]

#post_share[friend_circle_id][]
    @post.save!

    fail

  end

  def edit
  end

  def update
  end

  def show
  end

  def index
    @posts = [].tap do |posts_array|
      current_user.friend_circles.each do |circle|
        posts_array << circle.posts
      end
    end.flatten.uniq
    fail
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
    params[:user][:email],
    params[:user][:password]
    )

    if user.nil?
      # make teh errorz
      render :new
      return
    else
      login_user!(user)
      redirect_to user_url(user.id)
    end
  end

  def destroy
    current_user.generate_token
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def forgot_password

  end

  def send_email
    @user = User.find_by_email(params[:user][:email])
    if @user.nil?
      render :forgot_password
    else
      @user.generate_forgot_token
      msg = UserMailer.forgot_password(@user)
      msg.deliver!
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(params[:user])
    @post = Post.new(params[:post])
    @post.links.new(params[:link].values.compact)

    if @user.save
      @post.author_id = @user.id
      @post.save!
      fail
      login_user!(@user)
      flash[:notice] = "User successfully created"
      redirect_to user_url(@user)
    else
      flash[:errors] = "There was a problem"
      render :new
    end
  end

  def reset_password
    @user = User.find_by_forgot_password_token(params[:forgot_password_token])

    if @user.nil?
      render :json => "go away hacker"
    else
      render :reset_password
    end

  end

  def fix_password
    @user = User.find_by_email(params[:user][:email])
    @user.password = params[:user][:password]
    @user.save!
    redirect_to new_session_url
  end


  def edit
  end

  def update
  end

  def index
  end

  def show
    render :show
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=#{form_authenticity_token}".html_safe
  end


end

app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_circles/_form.html.erb
<%= action_url = @friend_circle.persisted? ? friend_circle_url(@friend_circle) : friend_circles_url %>

<form action="<%= action_url %>" method="post">

  <% if @friend_circle.persisted? %>
  <input type="hidden" name="_method" value="put">
  <% end %>
  <%= auth_token %>

  Select friends:<br>

  <input type="hidden" name="friend_circle[owner_id]" value="<%= current_user.id %>">

  <input type="hidden" name="friend_circle_memberships[member_ids][]" value="">
  <% @users.each do |user| %>
  <input type="checkbox" name="friend_circle_memberships[member_ids][]" value="<%= user.id %>"
  id="friend_circle_memberships_member_id_<%= user.id %>"
  <%= "checked" if @current_members.include?(user.id) %>>



  <label for="friend_circle_memberships_member_id_<%= user.id %>"><%= user.email %></label>
  <br>
  <% end %>

  <input type="Submit">

</form>

app/views/friend_circles/create.html.erb
<h1>FriendCircles#create</h1>
<p>Find me in app/views/friend_circles/create.html.erb</p>

app/views/friend_circles/destroy.html.erb
<h1>FriendCircles#destroy</h1>
<p>Find me in app/views/friend_circles/destroy.html.erb</p>

app/views/friend_circles/edit.html.erb
Edit
<p>

<%= render 'form', :friend_circle => @friend_circle %>

app/views/friend_circles/index.html.erb
<h1>FriendCircles#index</h1>
<p>Find me in app/views/friend_circles/index.html.erb</p>

app/views/friend_circles/new.html.erb
<%= render 'form', :friend_circle => @friend_circle %>


<!-- <form action="<%= friend_circles_url %>" method="post">
  <%= auth_token %>
  Select friends:<br>

  <input type="hidden" name="friend_circle[owner_id]" value="<%= current_user.id %>">

  <input type="hidden" name="friend_circle_memberships[member_id][]" value="">
  <% @users.each do |user| %>
  <input type="checkbox" name="friend_circle_memberships[member_id][]" value="<%= user.id %>" id="friend_circle_memberships_member_id_<%= user.id %>">


  <label for="friend_circle_memberships_member_id_<%= user.id %>"><%= user.email %></label>
  <br>
  <% end %>

  <input type="Submit" value="Create new friend circle">

</form> -->

app/views/friend_circles/show.html.erb
<h1>FriendCircles#show</h1>
<p>Find me in app/views/friend_circles/show.html.erb</p>

app/views/friend_circles/update.html.erb
<h1>FriendCircles#update</h1>
<p>Find me in app/views/friend_circles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialThing</title>
</head>
<body>

  <% unless current_user.nil? %>
  Current user:<%= current_user.id %><br>
  <% end %>
  Params: <%= params %><p>


  <% unless current_user.nil? %>
  <%= button_to "Log Out", session_url, method: :delete %>
  <%= link_to "Make new friend circle", new_friend_circle_url %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
  <!-- attr_accessible :author_id, :body, :title, :link_attributes -->
<% @posts.each do |post| %>


Body: <%= post.body %><br>
Author ID: <%= post.author_id %>
<br>
<ul>
<% post.links.each do |link| %>
<li> <%= link.url %>
</li>
<% end %>

</ul>
<% end %>

app/views/posts/new.html.erb
<form action="<%= posts_url %>" method="post">

  <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">
  <label for="body">Post body:</label>
  <input type="text" id="body" name="post[body]">

  Links:
  <% @post.links.each_with_index do |link, n| %>
    <label for="link_<%= n %>">Link <%= n %>: <input id="link_<%= n %>" name="link[<%= n %>][url]" type="text">
  <% end %>
  <br>
  Choose which friend circles to share this with:
  <% @user_friend_circles.each do |circle|%>
  <label for"post_share_id_<%= circle.id %>">Friend circle <%= circle.id %>:
  <input type="checkbox" name="post_share[friend_circle_id][]" value="<%= circle.id %>" id="post_share_id_<%= circle.id %>">

  <br>
  <% end %>
  <input type="submit">

  <%= auth_token %>

</form>

app/views/shared/_flashes.html.erb
<% if flash %>
<%= flash.each {|k,v| v } %><br />
<% end%>

app/views/users/new.html.erb
<%= render 'shared/flashes' %>

<h2> Sign up here </h2>

<form action="/users" method="post">

<label for="email">Email:</label>
<input type="text" id="email" name="user[email]">

<label for="password">Password:</label>
<input type="password" id="password" name="user[password]">

<label for="post_body">First Post(Body):</label>
<input type="text" id="post_body" name="post[body]">

Links:
<% 3.times do |n| %>
  <label for="link_<%= n %>">Link <%= n %>: <input id="link_<%= n %>" name="link[<%= n %>][url]" type="text">
<% end %>
<br>

<input type="submit" value="sign up">

<%= auth_token %>

</form>

app/views/users/reset_password.html.erb
<form action="<%= fix_password_users_url %>" method="get">

  <input type="hidden" name="user[email]" value="<%= @user.email %>">
  <input type="hidden" name="_method" value="put">

  <label for="user_password">Enter new password</label>
  <input type="text" name="user[password]">

  <input type="submit">
  <%= auth_token %>

</form>

app/views/users/show.html.erb
<%= render 'shared/flashes' %>

You are <%= current_user.email %>